#Location: .github/workflows/custom_config.yml

name: Build and push containers to Dockerhub
env:
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

on:
    push:
        branches:
            - master
            - include-sast
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: sast-scan
              uses: AppThreat/sast-scan-action@1.0.2
             
            - name: Git clone on our repo
              uses: actions/checkout@v2

            - name: Login to Dockerhub
              run: make login

            - name: Build Containers
              run: make build-amd64

            - name: Push Containers
              run: make push-amd64

            - name: SSH deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      docker service update --force --image ghcr.io/golemfactory/golem-stats-backend:${{ github.sha }} golemstats_webserver
                      docker service update --force --image ghcr.io/golemfactory/golem-stats-backend-celery:${{ github.sha }} golemstats_celery
                      docker service update --force --image ghcr.io/golemfactory/golem-stats-backend-celery-beat:${{ github.sha }} golemstats_celery_beat
                      docker service update --force --image ghcr.io/golemfactory/golem-stats-backend-celery-yagna:${{ github.sha }} golemstats_yagna_node
