#Location: .github/workflows/custom_config.yml

name: Build and push containers to Dockerhub
env:
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

on:
    push:
        branches:
            - master
            - include-sast
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
             
            - name: Git clone on our repo
              uses: actions/checkout@v2
            - name: sast-scan
              uses: AppThreat/sast-scan-action@1.0.2
            - name: SAST validator
              uses: michelleamesquita/sast-validator@v40
